
USE ROLE ECONOMIC_WRITE;
USE DATABASE ECONOMIC;
USE SCHEMA UTIL;

-- Openapi (invoice lines)
CALL UTIL.ECONOMIC_OPENAPI_DATAINGEST();
-- Rest (all other from economic)
CALL UTIL.ECONOMIC_RESTAPI_DATAINGEST();

-- Prestashop
CALL UTIL.PRESTASHOP_RESTAPI_DATAINGEST();