USE ROLE ACCOUNTADMIN;


-- Economic Appsecret
ALTER SECRET ECONOMIC_XAPIKEY_APPSECRET SET SECRET_STRING = 'YOUR_ACTUAL_APPSECRET_HERE';

-- Economic Agreement secret
ALTER SECRET ECONOMIC_XAPIKEY_AGREEMENTGRANT SET SECRET_STRING = 'YOUR_ACTUAL_AGREEMENTGRANT_HERE';

-- Presta secret
ALTER SECRET PRESTASHOP_WS_KEY SET SECRET_STRING = 'YOUR_ACTUAL_PRESTASHOP_WS_KEY_HERE';

USE ROLE ECONOMIC_WRITE;
USE DATABASE ECONOMIC;
USE SCHEMA UTIL;

CALL PRESTASHOP_RESTAPI_DATAINGEST();
CALL ECONOMIC_RESTAPI_DATAINGEST();
CALL ECONOMIC_OPENAPI_DATAINGEST();


USE ROLE ACCOUNTADMIN;
GRANT USAGE ON INTEGRATION ECONOMIC_API_INTEGRATION TO ROLE ECONOMIC_ADMIN;
GRANT USAGE ON INTEGRATION ECONOMIC_API_INTEGRATION TO ROLE ECONOMIC_WRITE;

-- Grant usage on PrestaShop API integration
GRANT USAGE ON INTEGRATION PRESTASHOP_API_INTEGRATION TO ROLE ECONOMIC_ADMIN;
GRANT USAGE ON INTEGRATION PRESTASHOP_API_INTEGRATION TO ROLE ECONOMIC_WRITE;