--7MM"""Yb.   `7MM"""YMM  `7MMF'   `7MF'  .g8""8q.   MMP""MM""YMM `7MM"""YMM        db      `7MMM.     ,MMF
-- MM    `Yb.   MM    `7    `MA     ,V  .dP'    `YM. P'   MM   `7   MM    `7       ;MM:       MMMb    dPMM
-- MM     `Mb   MM   d       VM:   ,V   dM'      `MM      MM        MM   d        ,V^MM.      M YM   ,M MM
-- MM      MM   MMmmMM        MM.  M'   MM        MM      MM        MMmmMM       ,M  `MM      M  Mb  M' MM
-- MM     ,MP   MM   Y  ,     `MM A'    MM.      ,MP      MM        MM   Y  ,    AbmmmqMA     M  YM.P'  MM
-- MM    ,dP'   MM     ,M      :MM;     `Mb.    ,dP'      MM        MM     ,M   A'     VML    M  `YM'   MM
--JMMmmmdP'   .JMMmmmmMMM       VF        `"bmmd"'      .JMML.    .JMMmmmmMMM .AMA.   .AMMA..JML. `'  .JMML

--  .M"""bgd `7MN.   `7MF'  .g8""8q.   `7MMF'     A     `7MF' .M"""bgd `7MMF'      `7MM"""YMM  `7MM"""Yb.
-- ,MI    "Y   MMN.    M  .dP'    `YM.   `MA     ,MA     ,V  ,MI    "Y   MM          MM    `7    MM    `Yb.
-- `MMb.       M YMb   M  dM'      `MM    VM:   ,VVM:   ,V   `MMb.       MM          MM   d      MM     `Mb
--   `YMMNq.   M  `MN. M  MM        MM     MM.  M' MM.  M'     `YMMNq.   MM          MMmmMM      MM      MM
-- .     `MM   M   `MM.M  MM.      ,MP     `MM A'  `MM A'    .     `MM   MM      ,   MM   Y  ,   MM     ,MP
-- Mb     dM   M     YMM  `Mb.    ,dP'      :MM;    :MM;     Mb     dM   MM     ,M   MM     ,M   MM    ,dP'
-- P"Ybmmd"  .JML.    YM    `"bmmd"'         VF      VF      P"Ybmmd"  .JMMmmmmMMM .JMMmmmmMMM .JMMmmmdP'


/*-----------------------------------------------------------------*/
/**                                                               **/
/***                                                             ***/
/*** THIS SCRIPT ARE TO BE EXECUTED ON A FRESH SNOWFLAKE ACCOUNT ***/
/*** IT WILL EXECUTE FILELIST FOR AUTOMATED FEATURE DEPLOYMENTS  ***/
/***                                                             ***/
/**                                                               **/
/*-----------------------------------------------------------------*/

USE ROLE ACCOUNTADMIN;
SET ADMINDBNAME = 'ADMIN';
SET ADMINSCHEMA = 'ADMIN';
SET ADMINNAMESPACE = CONCAT($ADMINDBNAME, '.', $ADMINSCHEMA);
SET ADMINWAREHOUSE = CONCAT($ADMINDBNAME, '_WH');
--SELECT $ADMINNAMESPACE;
--DROP DATABASE $ADMINNAMESPACE;

USE ROLE ACCOUNTADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE SYSADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE SYSADMIN;
ALTER SECURITY INTEGRATION IF EXISTS AZURE_ENTRAID_PROVISIONING UNSET NETWORK_POLICY;
DROP NETWORK POLICY IF EXISTS ALLOW_AZURE_ENTRAID_SCIM_ENDPOINTS;

/*** IF EXPECTED ROLES DOES NOT EXIST, USE BELOW TO POPULATE   ***/


USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($ADMINWAREHOUSE);
USE WAREHOUSE IDENTIFIER($ADMINWAREHOUSE);
DROP DATABASE IF EXISTS IDENTIFIER($ADMINDBNAME);
CREATE DATABASE IF NOT EXISTS IDENTIFIER($ADMINDBNAME);
USE DATABASE IDENTIFIER($ADMINDBNAME);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($ADMINNAMESPACE) WITH MANAGED ACCESS;
USE SCHEMA IDENTIFIER($ADMINNAMESPACE);

USE ROLE SYSADMIN;
GRANT ALL ON WAREHOUSE IDENTIFIER($ADMINWAREHOUSE) TO ROLE ACCOUNTADMIN WITH GRANT OPTION;
GRANT ALL ON DATABASE IDENTIFIER($ADMINDBNAME) TO ROLE ACCOUNTADMIN;
GRANT ALL ON SCHEMA IDENTIFIER($ADMINNAMESPACE) TO ROLE ACCOUNTADMIN;
GRANT USAGE, OPERATE ON WAREHOUSE IDENTIFIER($ADMINWAREHOUSE) TO ROLE SECURITYADMIN WITH GRANT OPTION;
GRANT USAGE ON DATABASE IDENTIFIER($ADMINDBNAME) TO ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA IDENTIFIER($ADMINNAMESPACE) TO ROLE SECURITYADMIN;


USE ROLE ACCOUNTADMIN;
GRANT CREATE GIT REPOSITORY ON SCHEMA IDENTIFIER($ADMINNAMESPACE) TO ROLE SYSADMIN;

USE ROLE ACCOUNTADMIN;
USE SCHEMA IDENTIFIER($ADMINNAMESPACE);
--DROP SECRET GIT_DEVOTEAM_SECRET;
CREATE OR REPLACE SECRET GIT_DEVOTEAM_SECRET
  TYPE = password
  USERNAME = ''
  PASSWORD = ''
  ;
GRANT USAGE ON SECRET GIT_DEVOTEAM_SECRET TO ROLE SYSADMIN;
--DESC SECRET GIT_DEVOTEAM_SECRET;

USE ROLE ACCOUNTADMIN;
USE SCHEMA IDENTIFIER($ADMINNAMESPACE);

--DROP INTEGRATION GIT_INTEGRATION_INVISODK;
CREATE OR REPLACE API INTEGRATION GIT_INTEGRATION_INVISODK
    API_PROVIDER = git_https_api
    API_ALLOWED_PREFIXES = ('https://github.com/invisodk/snowsled')
  ALLOWED_AUTHENTICATION_SECRETS = (GIT_DEVOTEAM_SECRET)
    ENABLED = TRUE
    COMMENT = 'connecting to Devoteam and Inviso GIT repos'
    ;
GRANT USAGE ON INTEGRATION GIT_INTEGRATION_INVISODK TO ROLE SYSADMIN;


USE ROLE SYSADMIN;
USE SCHEMA IDENTIFIER($ADMINNAMESPACE);
CREATE OR REPLACE GIT REPOSITORY DEVOTEAM_SNOWFLAKE_REPO
    API_INTEGRATION  = GIT_INTEGRATION_INVISODK
    git_credentials = GIT_DEVOTEAM_SECRET
    origin = 'https://github.com/invisodk/snowsled'
    ;
--SHOW GIT BRANCHES IN DEVOTEAM_SNOWFLAKE_REPO;


USE ROLE ACCOUNTADMIN;
USE SCHEMA IDENTIFIER($ADMINNAMESPACE);
ALTER GIT REPOSITORY DEVOTEAM_SNOWFLAKE_REPO FETCH;
--LS @devoteam_snowflake_repo/branches/master;

EXECUTE IMMEDIATE FROM @DEVOTEAM_SNOWFLAKE_REPO/branches/master/00_execute_all_files_in_repo.sql;
--EXECUTE IMMEDIATE FROM @DEVOTEAM_SNOWFLAKE_REPO/branches/master/ ;
/*
EXECUTE IMMEDIATE FROM @DEVOTEAM_SNOWFLAKE_REPO/branches/master/B_Snowflake_Projects/10_usp_javascript_create_db_config_roles.sql;
EXECUTE IMMEDIATE FROM @DEVOTEAM_SNOWFLAKE_REPO/branches/master/B_Snowflake_Projects/11_usp_javascript_create_dep_db_config_roles.sql;
EXECUTE IMMEDIATE FROM @DEVOTEAM_SNOWFLAKE_REPO/branches/master/B_Snowflake_Projects/12_usp_javascript_create_ingestion_db_config_roles.sql;
EXECUTE IMMEDIATE FROM @DEVOTEAM_SNOWFLAKE_REPO/branches/master/B_Snowflake_Projects/13_usp_sql_cursor_for_source_schemas.sql;
EXECUTE IMMEDIATE FROM @DEVOTEAM_SNOWFLAKE_REPO/branches/master/B_Snowflake_Projects/14_usp_sql_cursor_for_role_relations.sql;
EXECUTE IMMEDIATE FROM @DEVOTEAM_SNOWFLAKE_REPO/branches/master/B_Snowflake_Projects/15_usp_javascript_create_serviceuser.sql;
EXECUTE IMMEDIATE FROM @DEVOTEAM_SNOWFLAKE_REPO/branches/master/B_Snowflake_Projects/19_usp_javascript_generic_variable.sql;
CALL USE_OUTSIDE_VARIABLE(DBNAME => 'DATABASE', PROD_OR_DEV => 'PROD');
*/


USE ROLE SYSADMIN;
USE SCHEMA ADMIN.ADMIN;
CALL ADMIN.ADMIN.CREATE_DBSCHEMA_ROLECONFIG('DEVOTEAM');
/* USE ROLE ACCOUNTADMIN;
GRANT ROLE DEVOTEAM_ADMIN TO ROLE SYSADMIN;
--USE ROLE DEVOTEAM_ADMIN; DROP DATABASE DEVOTEAM;
*/
--SELECT * FROM ADMIN.ADMIN.DB_SCHEMA_OU_RELATIONS;
CALL ADMIN.ADMIN.CURS_CREATE_INGESTION_DBSCHEMA_FROM_LIST('DATALOAD', '');
CALL ADMIN.ADMIN.CURS_CREATE_DEPARTMENT_DBSCHEMA_FROM_LIST('DEVOTEAM', '');

/*
USE ROLE SYSADMIN;
CALL ADMIN.ADMIN.CREATE_DEPARTMENTDB_ROLECONFIG('DEVOTEAM', 'DATADRIVEN');
*/
/*
USE ROLE SYSADMIN;
USE SCHEMA ADMIN.ADMIN;
CALL ADMIN.ADMIN.CREATE_DBSCHEMA_ROLECONFIG('DEVO', 'DK');
USE ROLE SYSADMIN;
CALL ADMIN.ADMIN.CREATE_DEPARTMENTDB_ROLECONFIG('DEVO', 'CORP', 'DK');
*/

/*
SELECT "INGESTIONROLE", "DEPARTMENTROLE", "ACTIVERELATION" FROM ADMIN.ADMIN.DB_INGESTION_OU_RELATIONS ROLERELA
INNER JOIN "SNOWFLAKE"."ACCOUNT_USAGE"."ROLES" ROLEDEP ON ROLERELA."DEPARTMENTROLE" = ROLEDEP."NAME" INNER JOIN "SNOWFLAKE"."ACCOUNT_USAGE"."ROLES" ROLEING ON ROLERELA."INGESTIONROLE" = ROLEING."NAME" WHERE ROLEDEP."DELETED_ON" IS NULL AND ROLEDEP."OWNER" IS NOT NULL AND ROLEING."DELETED_ON" IS NULL AND ROLEING."OWNER" IS NOT NULL AND ROLERELA."ACTIVERELATION" = true ;
*/
--CALL CURS_REVOKE_ROLE_RELATIONS_FROM_LIST('DATALOAD');
CALL ADMIN.ADMIN.CURS_GRANT_ROLE_RELATIONS_FROM_LIST('DATALOAD');



USE ROLE SYSADMIN;
CALL ADMIN.ADMIN.LIST_ASSIGNED_USERROLES();
--CALL ADMIN.ADMIN.CREATE_ADMIN_USER('DEVOTEAM');
/*
SELECT * FROM DEVO.PUBLIC.ASSIGNED_CUSTOM_ROLES;
SELECT * FROM DEVO.PUBLIC.CUSTOM_DATABASE_LIST;
SELECT * FROM DEVO.PUBLIC.CUSTOM_ROLE_MEMBERSHIPS;
SELECT * FROM DEVO.PUBLIC.USERS_IN_DATABASE;
SELECT * FROM DEVOTEAM.PUBLIC.USERS_IN_DATABASE;
SELECT * FROM ADMIN.PUBLIC.USERS_IN_DATABASE;
*/
USE ROLE ACCOUNTADMIN;
DROP GIT REPOSITORY IF EXISTS DEVOTEAM_SNOWFLAKE_REPO;
DROP INTEGRATION IF EXISTS GIT_INTEGRATION_INVISODK;
DROP SECRET IF EXISTS GIT_DEVOTEAM_SECRET;